config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'home#index', as: 'home'
  # get 'about', to: 'home#about'
  get 'tariff', to: 'home#tariff'

  namespace :admins do
    resources :drivers do
      collection do
        get :statistic
      end
    end

    resources :feedbacks
    resources :passengers
    resources :orders
    resources :tariffs

    root "orders#index"
  end

  namespace :passengers do
    resources :orders do
      resources :feedbacks, only: %i[create]

      get 'geocode_address', to: 'orders#geocode_address'
      get 'calculate_price', to: 'orders#calculate_price'
    end
  end

  namespace :drivers do
    resources :orders, except: %i[new create destroy] do
      resources :feedbacks, only: %i[create]

      member do
        get :change_order_status
      end
    end
  end
end

app/models/driver.rb
class Driver < User
  belongs_to :tariff
  has_many :orders, dependent: :nullify
  has_many :feedbacks, dependent: :nullify

  def driver_salary
    (price_per_this_month_for_driver - price_per_this_month_for_driver * 0.1).to_d
  end

  private

  def price_per_this_month_for_driver
    Order.where("created_at >= ? AND created_at < ?",
                Time.zone.now.beginning_of_month, Time.zone.now.end_of_month)\
         .where(driver_id: id).sum(:price)
  end
end

app/controllers/admins/drivers_controller.rb
module Admins
  class DriversController < Admins::ApplicationController
    def statistic
      @drivers = Driver.all
      @drivers_data = DriversTotalFetcherService.fetch
    end
  end
end

app/controllers/drivers/drivers_controller.rb
module Drivers
  class DriversController < ApplicationController; end
end

app/controllers/drivers/feedbacks_controller.rb
module Drivers
  class FeedbacksController < DriversController
    def create
      @order    = Order.find(params[:order_id])
      @feedback = @order.feedbacks.create(feedback_params)

      if @feedback.save
        redirect_to [:drivers, @order], notice: 'Feedback was successfully created.'
      else
        redirect_to [:drivers, @order], notice: 'Something was wrong.'
      end
    end

    private

    def feedback_params
      params.require(:feedback).permit(:rating, :text, :passenger_id, :driver_id)
    end
  end
end

app/controllers/drivers/orders_controller.rb
module Drivers
  class OrdersController < DriversController
    before_action :find_order, only: %i[show edit update change_order_status]

    def index
      @orders = Order.where(tariff_id: current_user.tariff_id).reverse
    end

    def show; end

    def edit; end

    def change_order_status
      @order.driver_id = current_user.id if @order.state == Order::CREATED_STATE
      @order.change_status
      redirect_to drivers_order_path
    end

    def update
      if @order.update(order_params)
        redirect_to @order, notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    private

    def find_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:passenger_id, :driver_id, :starting_address, :destination_address,
                                    :tariff_id, :price, :state)
    end
  end
end

app/views/shared/driver/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.shadow.mb-4.bg-white.rounded
  .container-fluid
    %a.font-weight-bold.d-flex.flex-row.d-flex.align-items-center.navbar-brand{href: home_path}
      %h3.text-warning Ultimate
      %h3.text-dark TAXI
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        -# %li.nav-item
        -#   = link_to 'About us', about_path, class: 'nav-link active'
        %li.nav-item
          = link_to 'Tariffs', tariff_path, class: 'nav-link active'
        -# %li.nav-item
        -#   %a.nav-link.disabled{"aria-disabled" => "true", href: "#", tabindex: "-1"} Disabled
        %li.nav-item
          = link_to 'Orders', drivers_orders_path, class: 'nav-link active'
    %form.d-flex.flex-row.justify-content-end
      = link_to "Your salary per this month: #{current_user.driver_salary} UAH", "", class: 'btn btn-outline-block text-muted mr-2'
      = link_to 'Profile', edit_user_registration_path, class: 'btn btn-outline-warning mr-2'
      = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark'