config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'home#index', as: 'home'
  # get 'about', to: 'home#about'
  get 'tariff', to: 'home#tariff'

  namespace :admins do
    resources :drivers do
      collection do
        get :statistic
      end
    end

    resources :feedbacks
    resources :passengers
    resources :orders
    resources :tariffs

    root "orders#index"
  end

  namespace :passengers do
    resources :orders do
      resources :feedbacks, only: %i[create]

      get 'geocode_address', to: 'orders#geocode_address'
      get 'calculate_price', to: 'orders#calculate_price'
    end
  end

  namespace :drivers do
    resources :orders, except: %i[new create destroy] do
      resources :feedbacks, only: %i[create]

      member do
        get :change_order_status
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  CREATED_STATE           = 'created'.freeze
  ACCEPTED_STATE          = 'accepted'.freeze
  WAITING_PASSENGER_STATE = 'waiting_passenger'.freeze
  MOVING_STATE            = 'moving'.freeze
  FINISHED_STATE          = 'finished'.freeze

  ORDERS_FEE = 0.1

  has_many :feedbacks, dependent: :nullify

  belongs_to :driver, optional: true
  belongs_to :passenger
  belongs_to :tariff

  delegate :name, :cost, to: :tariff, prefix: true

  validates :starting_address, presence: true
  validates :destination_address, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  include AASM

  aasm column: 'state' do
    state :created, initial: true
    state :accepted
    state :waiting_passenger
    state :moving
    state :finished

    event :accept do
      transitions from: :created, to: :accepted
    end

    event :wait_passenger do
      transitions from: :accepted, to: :waiting_passenger
    end

    event :move do
      transitions from: :waiting_passenger, to: :moving
    end

    event :finish, after: :send_order_finished_email_to_passenger do
      transitions from: :moving, to: :finished
    end
  end

  def change_status
    case state
    when CREATED_STATE
      accept!
    when ACCEPTED_STATE
      wait_passenger!
    when WAITING_PASSENGER_STATE
      move!
    else
      finish!
    end
  end

  class << self
    # Total calculating

    def total_price
      Order.group(:driver_id).sum(:price)
    end

    def total_prices_fee
      total_price.transform_values { |sum| OrdersFeeCalculatorService.calculate_fee(sum) }
    end

    def total_price_salary
      total_price.transform_values { |sum| (sum - OrdersFeeCalculatorService.calculate_fee(sum)) }
    end

    # Calculating for this month

    def price_per_this_month
      Order.where("created_at >= ? AND created_at < ?",
                  Time.zone.now.beginning_of_month, Time.zone.now.end_of_month)\
           .group(:driver_id).sum(:price)
    end

    def fee_per_this_month
      price_per_this_month.transform_values { |sum| OrdersFeeCalculatorService.calculate_fee(sum) }
    end

    def salary_per_this_month
      price_per_this_month.transform_values { |sum| (sum - OrdersFeeCalculatorService.calculate_fee(sum)) }
    end

    # Calculating for last month

    def price_per_last_month
      Order.where("created_at >= ? AND created_at < ?",
                  (Time.zone.now - 1.month).beginning_of_month,
                  (Time.zone.now - 1.month).end_of_month).group(:driver_id).sum(:price)
    end

    def fee_per_last_month
      price_per_last_month.transform_values { |sum| OrdersFeeCalculatorService.calculate_fee(sum) }
    end

    def salary_per_last_month
      price_per_last_month.transform_values { |sum| (sum - OrdersFeeCalculatorService.calculate_fee(sum)) }
    end
  end

  private

  def send_order_finished_email_to_passenger
    OrderMailer.send_order_finished_email(self).deliver_now
  end
end

app/models/passenger.rb
class Passenger < User
  has_many :orders, dependent: :nullify
  has_many :feedbacks, dependent: :nullify
end

app/controllers/admins/orders_controller.rb
module Admins
  class OrdersController < Admins::ApplicationController; end
end

app/controllers/admins/passengers_controller.rb
module Admins
  class PassengersController < Admins::ApplicationController; end
end

app/controllers/drivers/orders_controller.rb
module Drivers
  class OrdersController < DriversController
    before_action :find_order, only: %i[show edit update change_order_status]

    def index
      @orders = Order.where(tariff_id: current_user.tariff_id).reverse
    end

    def show; end

    def edit; end

    def change_order_status
      @order.driver_id = current_user.id if @order.state == Order::CREATED_STATE
      @order.change_status
      redirect_to drivers_order_path
    end

    def update
      if @order.update(order_params)
        redirect_to @order, notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    private

    def find_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:passenger_id, :driver_id, :starting_address, :destination_address,
                                    :tariff_id, :price, :state)
    end
  end
end

app/controllers/passengers/feedbacks_controller.rb
module Passengers
  class FeedbacksController < PassengersController
    def create
      @feedback = Feedback.create(order_id: params[:order_id])

      if @feedback.save
        redirect_to [:passengers, @order], notice: 'Feedback was successfully created.'
      else
        redirect_to [:passengers, @order], notice: 'Something was wrong.'
      end
    end
  end
end

app/controllers/passengers/orders_controller.rb
module Passengers
  class OrdersController < PassengersController
    def index
      @orders = Order.where(passenger_id: current_user.id)
    end

    def show
      @order = Order.find(params[:id])

      respond_to do |format|
        format.html
        format.pdf { render_pdf }
      end
    end

    def new
      @order = Order.new
    end

    def create
      @order                     = Order.new(order_params)
      @order.passenger           = current_user
      convert_address_to_coordinates

      if @order.save
        redirect_to [:passengers, @order], notice: 'Order was successfully created.'
      else
        render :new
      end
    end

    def geocode_address
      render json: AddressGeocoderService.new(params[:address]).geocode.to_json
    end

    def calculate_price
      render json: CalculatePriceService.new(params[:starting_address],
                                             params[:destination_address],
                                             params[:tariff]).calculate.to_json
    end

    private

    def convert_address_to_coordinates
      @order.starting_address    = order_params[:starting_address].split(',').last(2).map(&:to_f)
      @order.destination_address = order_params[:destination_address].split(',').last(2).map(&:to_f)
    end

    def render_pdf
      render pdf: "Receipt",
             page_width: '8in',
             page_height: '5in',
             template: "passengers/orders/receipt_pdf.html.haml",
             layout: "receipt_pdf.html.haml",
             orientation: "Landscape",
             lowquality: true, zoom: 1,
             dpi: 75, encoding: 'utf8'
    end

    def order_params
      params.require(:order).permit(:passenger_id, :driver_id, :starting_address, :destination_address,
                                    :tariff_id, :price, :state)
    end
  end
end

app/controllers/passengers/passengers_controller.rb
module Passengers
  class PassengersController < ApplicationController; end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def get_human_readable_state(state)
    case state
    when Order::CREATED_STATE
      "Created"
    when Order::ACCEPTED_STATE
      "Accepted"
    when Order::WAITING_PASSENGER_STATE
      "Waiting passenger"
    when Order::MOVING_STATE
      "Moving"
    else
      "Finished"
    end
  end
end

app/views/passengers/orders/index.html.haml
.content.jumbotron.jumbotron-fluid.bg-light.pt-1
  .container.d-flex.flex-row.justify-content-center.pb-4
    %h2.font-weight-bold.text-warning.mr-3 List of your
    %h2.font-weight-bold.text-dark.mb-4 all orders
  .row.w-75.mx-auto
    %table.table.mx-auto
      - @orders.each do |order|
        %tr
          %td.table-borderless
            %h4.font-weight-bold.text-warning
              Name:
          %td.lead
            = order.passenger.first_name
          %td
            %h4.font-weight-bold.text-warning
              From:
          %td.lead
            = order.starting_address
          %td.text-center
            .div.row.pl-3
              %h4.font-weight-bold.text-warning
                Price:
              %h4.font-weight-bold.pl-5
                = order.price
                UAH.
        %tr.table-borderless
          %td
            %h4.font-weight-bold.text-warning.mb-4
              Surname:
          %td.lead
            = order.passenger.last_name
          %td
            %h4.font-weight-bold.text-warning.mb-4
              To:
          %td.lead
            = order.destination_address
          %td.text-center
            = link_to "Show order", passengers_order_path(order),
              class: 'btn btn-dark text-warning font-weight-bold mb-4'

app/views/passengers/orders/new.html.haml
.content.jumbotron.jumbotron-fluid.bg-light.pt-1
  .container.d-flex.flex-row.justify-content-center
    %h2.font-weight-bold.text-warning.mr-3 Create
    %h2.font-weight-bold.text-dark.mb-5 Order
  .row.w-100
    .content.jumbotron.jumbotron-fluid.w-25.mx-auto.shadow.bg-light.rounded.px-5
      = simple_form_for [:passengers, @order], data: { controller: 'orders' } do |o|
        = o.error_notification
        .field
          = o.label :starting_address, class: 'text-muted'
          %br/
          = o.input_field :starting_address, autocomplete: "starting_address", class: 'form-control input-prop', id: 'starting_address'
        .field
          = o.label :destination_address, class: 'text-muted mt-2'
          %br/
          = o.input_field :destination_address, autocomplete: "destination_address", class: 'form-control input-prop', id: 'destination_address'
        .field.m-0.row
          = o.label :tariff, class: 'text-muted'
          %br/
          = collection_select(:order, :tariff_id, Tariff.all, :id, :name, {include_blank: false}, {class: "form-control mw-100 px-2"})
        .field
          = o.label :price, class: 'text-muted mt-2'
          %br/
          = o.input_field :price, class: 'form-control input-prop', id: 'price'
        .actions.text-center
          = o.submit 'Create order', class: 'btn btn-warning px-5 mt-4'
    .content.jumbotron.jumbotron-fluid.w-50.p-0.bg-light.mx-auto
      %p#map.bg-light.shadow.bg-white.rounded
        %script{ async: "", src: "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAP_API_KEY']}&region=UK&language=uk&callback=initMap&libraries=&v=weekly" }

app/views/passengers/orders/receipt_pdf.html.haml
%h1 ULTIMATE TAXI
%h2 ########## Receipt № #{ @order.id } ##########
%br/
%p
  %b
    Date:
  #{ @order.updated_at }
%br/
%p
  %b
    Passenger first name:
  #{ @order.passenger.first_name }
%p
  %b
    Passenger last name:
  #{ @order.passenger.last_name }
%br/
%p
  %b
    Driver first name:
  #{ @order.driver.first_name }
%p
  %b
    Driver last name:
  #{ @order.driver.last_name }
%br/
%p
  %b
    Tariff name:
  #{ @order.tariff_name }
%p
  %b
    Tariff cost:
  #{ @order.tariff_cost } UAH/km
%br/
%p
  %b
    Starting address:
  #{ @order.starting_address }
%p
  %b
    Destination address:
  #{ @order.destination_address }
%br/
%hr/
%h2
  Price: #{ @order.price } UAH

app/views/passengers/orders/show.html.haml
.content.jumbotron.jumbotron-fluid.bg-light.pt-1.mb-0
  .container.d-flex.flex-row.justify-content-center.mb-3
    %h2.font-weight-bold.text-warning.mr-3 Your
    %h2.font-weight-bold.text-dark.mb-5 Order
  .row.w-100
    .div.col-sm-5.mx-auto.shadow.mb-4.bg-light.rounded.py-4
      %table.table-borderless.mx-auto.px-3
        %tr
          %td
            %p.lead.font-weight-bold
              Passenger:
          %td
            %p.lead
              = @order.passenger.first_name
              = @order.passenger.last_name
              &nbsp;
        %tr
          %td
            %p.lead.font-weight-bold
              Orders status:
          %td
            %p.lead
              = get_human_readable_state(@order.state)
              &nbsp;
        %tr
          %td
            %p.lead.font-weight-bold
              Starting address:
          %td
            %p.lead
              = Geocoder.address(@order.starting_address)
              &nbsp;
        %tr
          %td
            %p.lead.font-weight-bold
              Destination address:
          %td
            %p.lead
              = Geocoder.address(@order.destination_address)
              &nbsp;
        %tr
          %td
            %p.lead.font-weight-bold
              Tariff:
          %td
            %p.lead
              = @order.tariff.cost
              UAH / km.
        %tr
          %td
            %p.lead.font-weight-bold
              Price:
          %td
            %p.lead.font-weight-bold
              = @order.price
              UAH.
        %tr
          %td
            %p.lead.font-weight-bold
              Driver:
          %td
            - if @order.driver_id?
              %p.lead
                = @order.driver.first_name
                = @order.driver.last_name
            - else
              %p.lead
                &nbsp;
    .div.col-sm-5.mx-auto.px-4
      .container.d-flex.bg-light.w-100.h-100.justify-content-center
        = image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=12&size=450x200&scale=2&markers=size:mid%7Ccolor:red%7Clabel:A%7C#{@order.starting_address[1..-2]}&markers=size:mid%7Ccolor:red%7Clabel:B%7C#{@order.destination_address[1..-2]}&path=color:0xff0000ff|weight:2|#{@order.starting_address[1..-2]}|#{@order.destination_address[1..-2]}&key=#{ENV['GOOGLE_MAP_API_KEY']}&region=UK&language=uk",
                    alt: "Map", class: "shadow mb-4 bg-white rounded"

    - if @order.finished?
      .row.w-100.mt-4
        .col-sm-5.mx-auto
          %h3.text-warning.font-weight-bold.text-right
            My receipt:
        .col-sm-5.mx-auto
          = link_to 'Show receipt', passengers_order_path(@order, format: :pdf),
            class: 'btn-lg btn-dark text-warning font-weight-bold'

      .content.jumbotron.jumbotron-fluid.w-75.mx-auto.shadow.bg-light.rounded.px-5.pt-2.mt-5
        .container.d-flex.flex-row.justify-content-center
          %h2.font-weight-bold.text-warning.mr-3 Your
          %h2.font-weight-bold.text-dark.mb-5 Feedback
        = render @order.feedbacks
        = render '/passengers/feedbacks/new', order: @order