config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'home#index', as: 'home'
  # get 'about', to: 'home#about'
  get 'tariff', to: 'home#tariff'

  namespace :admins do
    resources :drivers do
      collection do
        get :statistic
      end
    end

    resources :feedbacks
    resources :passengers
    resources :orders
    resources :tariffs

    root "orders#index"
  end

  namespace :passengers do
    resources :orders do
      resources :feedbacks, only: %i[create]

      get 'geocode_address', to: 'orders#geocode_address'
      get 'calculate_price', to: 'orders#calculate_price'
    end
  end

  namespace :drivers do
    resources :orders, except: %i[new create destroy] do
      resources :feedbacks, only: %i[create]

      member do
        get :change_order_status
      end
    end
  end
end

app/controllers/admins/application_controller.rb
module Admins
  class ApplicationController < Administrate::ApplicationController; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :choose_layout

  def after_sign_in_path_for(_resource)
    current_user.admin? ? admins_root_path : home_path
  end

  def choose_layout
    if !user_signed_in?
      'application'
    elsif current_user.driver?
      'driver'
    elsif current_user.passenger?
      'passenger'
    end
  end

  add_flash_types :danger, :info, :warning, :success
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/application/_collection.html.erb
<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: resource_class.human_attribute_name(attr_name),
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          <% if show_action? :show, resource %>
            <%= %(tabindex=0 role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 tabindex="-1"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% else %>
              <%= render_field attribute %>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/application/_form.html.erb
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name, singular: true)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/application/_navigation.html.erb
<nav class="navigation" role="navigation">
  <%= link_to('Log out', destroy_user_session_path, method: :delete, class: "button button--alt") if defined?(home_url) %>
  <% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      resource_index_route(resource),
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) if valid_action?(:index, resource) && show_action?(:index, model_from_resource(resource)) %>
  <% end %>
  <%= link_to('Drivers statistic', statistic_admins_drivers_path, class: "navigation__link")%>
</nav>

app/views/admins/application/edit.html.erb
<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admins/application/index.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: display_resource_name(page.resource_name, singular: true).downcase
      ),
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources, param_name: '_page' %>
</section>

app/views/admins/application/new.html.erb
<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admins/application/show.html.erb
<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: page.resource.class.human_attribute_name(attribute.name),
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>